### ISSUE TITLE
cgi example

### ISSUE THREAD

**Issue by mouse170** [mmaelzer/motion#2]
Hello, is there any example of videostream.cgi for this repo?
I don't know how to create it, thanks.

**Comment by mmaelzer** [comment]
There's no example video stream provided. However, you can find plenty of public mjpeg cameras for testing like [here]((http://www.mjpeg.net/)) or [here](http://en.ipcams.ch/). The only downside of using public cameras is the unpredictable nature of the motion which makes testing hard.
