### ISSUE TITLE
Some small issues with resulting JPEG files

### ISSUE THREAD

**Issue by dougmolineux** [mmaelzer/motion#4]
Firstly, thank you very much for putting this together, I've been experimenting with it for the past couple days, and it has really surpassed my expectations. I really appreciate the time you've put into it, and I would love to help with anything moving forward.

I am testing out the Usage example (under "Motion Stream") where we write images to a file:

`request(options).pipe(consumer).pipe(motion).pipe(writer);`

I have found that I am sometimes getting JPEGs that are invalid. I'm not quite sure where in the process something goes wrong, but upon converting the JPEGs into a GIF using this command:

`convert -delay 3 -loop 0 video/*.jpg monday.gif`

Several of the file conversion produces errors that look like this:

> convert: Not a JPEG file: starts with 0x34 0x38 video/1457373787249.jpg' @ error/jpeg.c/JPEGErrorHandler/322.
> convert: Not a JPEG file: starts with 0x5f 0x30 video/1457373788733.jpg' @ error/jpeg.c/JPEGErrorHandler/322.
> convert: Not a JPEG file: starts with 0x36 0x0d video/1457373789767.jpg' @ error/jpeg.c/JPEGErrorHandler/322.
> convert: Not a JPEG file: starts with 0x3a 0x30 video/1457373792936.jpg' @ error/jpeg.c/JPEGErrorHandler/322.

I don't mind digging around to investigate this issue, but I was wondering if you knew what could be happening? Or possibly what part of the process could lead to resulting in corrupted jpeg images?

Thank you very much again,
Doug

**Comment by mmaelzer** [comment]
Hey Doug!

Those issues appear to be the result of an old bug in the [mjpeg-consumer](https://github.com/mmaelzer/mjpeg-consumer) package. I updated the versions in `package.json` and tested locally with node v4, and everything appears a-ok.

After reinstalling dependencies, let me know if you still see the same issues with the jpegs, and I'll be happy to investigate further.

**Comment by dougmolineux** [comment]
Fantastic! Thanks so much for the quick response, I'll pull down your updates and try again!
