### ISSUE TITLE
Issues with stray line in motion.js

### ISSUE THREAD

**Issue by andrewferrier** [mmaelzer/motion#6]
Hi, it appears there is an inconsistency between the version of motion-detect on GitHub and the version on npm.

I've traced it to the stray line `if(img1.length !== img2.length) return null;` in `lib/motion.js` (which is I assume should *not* be present and is a bug. The version of `motion.js` (which corresponds to a `package.json` of 0.2.4) on GitHub does not have this line, but the version downloaded via `npm install` does.

Thanks for your work on this great library.

**Comment by andrewferrier** [comment]
Ignore the previous title, it came from when I thought the issue was different.

**Comment by mmaelzer** [comment]
Thanks for pointing out the problem! I've published the latest changes to npm. Let me know if you find any other issues.
